### ISSUE TITLE
Unable to start supabase cli on first Windows startup: Ports are not available

### ISSUE THREAD

**Issue by vhpx** [supabase/cli#1010]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

There is an error from daemon (ports are not available) that prevented the cli from running on every first Windows startup (It fixes itself after an OS restart). This happens I run `pnpm supabase start` in my working directory, which produces the following output:

```bash
Error: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:54322 -> 0.0.0.0:0: listen tcp 0.0.0.0:54322: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Try rerunning the command with --debug to troubleshoot the error.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

## To Reproduce

1. Boot into Windows after an OS shutdown
2. Run `pnpm supabase start` or equivalent script
3. See the error

## Expected behavior

The cli should start without any problem.

## System information

- OS: Windows 11, 22H2 (Build 22621.1485)
- Version of supabase-js: v1.50.2
- Version of Node.js: v19.8.1
- Version of pnpm: v8.2.0

## Additional context

This wasn't a problem in some earlier versions of the cli (the issue surfaced for 1-2 weeks before the cli v1.50.2, I'm not sure what was the last stable version that did not have this issue).

**Comment by soedirgo** [comment]
This seems related to https://github.com/supabase/cli/issues/189. Can you try running `supabase start` after changing the ports in `config.toml`?

**Comment by vhpx** [comment]
Changing the ports did work, but it took some manual work to determine what range was acceptable and what was not. Ultimately, I finally decided to go with the following configurations as they worked for me:

```toml
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "app"

[api]
# Port to use for the API URL.
port = 50501
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 50502
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 50503

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 50504
smtp_port = 50505
pop3_port = 50506

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""
```

Feel free to close this issue.
