### ISSUE TITLE
Inconsistent Generated Types Between Local Environment and GitHub CI Workflow in Supabase CLI

### ISSUE THREAD

**Issue by tiakindele** [supabase/cli#1146]
The Supabase CLI generates different types in the local environment compared to those generated in the GitHub Continuous Integration (CI) environment. This inconsistency causes the GitHub CI workflow script to fail.

**To Reproduce**
1. Create a new branch so that you can make a pull request
2. Run `supabase gen types typescript --local --schema 'public' > src/utils/types_db.ts` locally
3. Create the following file `.github/workflows/ci.yaml` with the following
    ```
    name: CI

    on:
      pull_request:
      workflow_dispatch:

    jobs:
      test:
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v3

          - uses: supabase/setup-cli@v1

          - name: Start Supabase local development setup
            run: supabase start

          - name: Verify generated types are up-to-date
            run: |
              supabase gen types typescript --local --schema 'public' > src/utils/types_db.ts
              if [ "$(git diff --ignore-space-at-eol src/utils/types_db.ts | wc -l)" -gt "0" ]; then
                echo "Detected uncommitted changes after build. See status below:"
                git diff
                exit 1
              fi
    ```
4. Push these changes to GitHub.
5. Observe the error occurring in the GitHub CI workflow (as shown in the attached screenshot).

**Expected behavior**
The script should generate the same types in the GitHub CI environment as it does locally and subsequently pass the workflow.

**Screenshots**
Attached is a screenshot of the GitHub CI workflow failing due to this issue:
<img width="1723" alt="screenshot-2023-05-24-16 45 05" src="https://github.com/supabase/cli/assets/18653558/64324ad0-4312-4d7f-8054-0537bec671a5">

**Desktop (please complete the following information):**
 - OS: Mac OS 13.2.1
 - Version of CLI: 1.50.10
 - Version of supabase-js: v2.4.1
 - Version of Node.js: v14.17.6
