### ISSUE TITLE
version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by Olyno** [supabase/cli#1306]
**Describe the bug**

It seems that Supabase CLI no longer supports older versions of Debian. I'm using Deepin OS based on Debian 10 and after updating the CLI, I get the following errors:

```
supabase: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by supabase)
supabase: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by supabase)
```

**To Reproduce**
1. Use latest version
2. Error

**Expected behavior**

Could be awesome if we still can support "old" OS.

**Screenshots**

/

**Desktop (please complete the following information):**
 - OS: Deepin (Debian 10)
 - Browser (if applicable): /
 - Version of CLI 1.77.6
 - Version of supabase-js (if applicable): /
 - Version of Node.js (if applicable): 16.20.1

**Additional context**

/

**Comment by sweatybridge** [comment]
Thank you for raising this issue. I've enabled static linking in cli v1.77.8 so it doesn't depend on glibc at runtime.

**Comment by reubendrummond** [comment]
Encountered this error message in Bitbucket pipeline. Updated download script to 
```
npm install --location=global supabase@1.77.8
```
and error still exists. Can any assistance be offerred @sweatybridge? Thanks

**Comment by sweatybridge** [comment]
Could you share with the full error logs from bitbucket here? Including the command you used to run and `npx supabase -v`

**Comment by reubendrummond** [comment]
No worries. 

pipeline config:
```
image: node:16.16.0
pipelines:
  branches:
    development:
      - step:
          name: Apply DB migrations in development
          script:
            - export SUPABASE_ACCESS_TOKEN=$SUPABASE_DEVELOPMENT_ACCESS_TOKEN
            - export SUPABASE_DB_PASSWORD=$SUPABASE_DEVELOPMENT_DB_PASSWORD
            - npm install --location=global supabase@1.77.8
            - npx supabase -v
            - npx supabase link --project-ref $SUPABASE_DEVELOPMENT_PROJECT_ID
            - npx supabase db push
 ```

err:
```
npx supabase -v
npm WARN exec The following package was not found and will be installed: supabase
supabase: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by supabase)
supabase: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by supabase)
```
