### ISSUE TITLE
Cannot use environment variables in config.toml

### ISSUE THREAD

**Issue by azlekov** [supabase/cli#1319]
**Describe the bug**

After following this [guide](https://supabase.com/docs/guides/cli/using-environment-variables-in-config) over a newly generated project and adjust twilio for authentication:

```toml
[auth.sms.twilio]
enabled = true
account_sid = "redacted"
message_service_sid = "redacted"
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"
```

I cannot get `supabase start/stop` running

**To Reproduce**
1. Following this [guide](https://supabase.com/docs/guides/cli/using-environment-variables-in-config)
2. Create `.env` file into supabase folder
3. Add `SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN`
4. Run `supabase start`
5. See error

**Expected behavior**

The local development to be up and running

**Screenshots**

```
Error evaluating "env(env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN))": environment variable SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN is unset. Try rerunning the command with --debug to troubleshoot the error.
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser (if applicable): not applicable
 - Version of CLI: 1.77.9
 - Version of supabase-js: not applicable
 - Version of Node.js: not applicable

**Additional context**

I'm using `fish`. `source .env && supabase start` does not work on the fish, trying to set the variable using `set` and run `supabase start` doest not fix the issue. Probably is parsing issue or something regarding reading the `toml` file

**Comment by sweatybridge** [comment]
Hi @azlekov, perhaps it wasn't clearly mentioned in our guide but `.env` file should be saved under project's root directory instead of `supabase/.env`. For eg.

```bash
project/
├─ supabase/
│  ├─ migrations/
│  ├─ config.toml
├─ .env
```

The main reason for this location is that some of the env vars may be reused by your application code outside of supabase. I will update the docs to be clearer.

Hope it helps.

**Comment by TikiCat7** [comment]
still facing this issue even with the .env in the root

**Comment by sweatybridge** [comment]
@TikiCat7 could you share with me the config fields you are trying to substitute? We only support a few [config fields](https://github.com/supabase/cli/blob/main/internal/utils/config.go#L410) at the moment but we can look into adding more.

**Comment by TikiCat7** [comment]
``` toml
[auth.external.github]
enabled = true
client_id = "env(SUPABASE_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_GITHUB_SECRET)"
```

**Comment by sweatybridge** [comment]
Could you also check the output of the following command? If it prints the secrets correctly, then the problem might be somewhere else

```bash
$ docker inspect supabase_auth_<project> | grep APPLE
                "GOTRUE_EXTERNAL_APPLE_ENABLED=true",
                "GOTRUE_EXTERNAL_APPLE_CLIENT_ID=<redacted>",
                "GOTRUE_EXTERNAL_APPLE_SECRET=<redacted>",
                "GOTRUE_EXTERNAL_APPLE_REDIRECT_URI=http://localhost:54321/auth/v1/callback",
```

Otherwise, could you also share the host OS and CLI version you are running?

**Comment by TikiCat7** [comment]
based on your comment I changed the key in `config.toml` to 
``` toml
client_id = "env(GOTRUE_EXTERNAL_GITHUB_CLIENT_ID)"
secret = "env(GOTRUE_EXTERNAL_GITHUB_SECRET)"
```
Added these to a `.env` file in the root folder and supabase is starting with the correct values. (.env.local doesn't seem to work though). So is the issue that `config.toml` shows different names from what supabase is expecting?
