### ISSUE TITLE
GitHub Actions with CLI

### ISSUE THREAD

**Issue by besteman** [supabase/cli#147]
# Improve documentation

## Link 

https://github.com/supabase/cli/tree/main/examples/tour

## Describe the problem

No steps or docs on CI with CLI/migrations

## Describe the improvement

I would like to add a section on how to setup GitHub to these docs

Hello,

I was wondering how I would make a CI flow with GitHub Actions.

The basic flow is the following:
(all after the installing, init, and start)
1. Local Changes to DB
2. Supabase CLI: supabase db commit <migration name>
3. Commit to source control (git)
4. Open a PR and reviewed
5. Once merged into the master/main branch, Github Actions runs a migration to Supabase project DB

I have come up with the following yml for the flow:

```yml
name: Migration for Prod DB

on:
  push:
    branches: [ master ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          migrations:
            - 'supabase/migrations/**'

  migration:
    needs: changes
    if: ${{ needs.changes.outputs.migrations == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Supabase CLI
        run: brew install supabase/tap/supabase
      - name: Set Remote DB
        shell: bash
        env:
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase db remote set 'postgresql://postgres:"$SUPABASE_PASSWORD"@db."$SUPABASE_PROJECT_REF".supabase.co:5432/postgres'
      - name: Push Migrations
        run: supabase db push
```

Would this be the approach to take? If so, I will make a PR for it in the docs
