### ISSUE TITLE
Ignore function when deploy all

### ISSUE THREAD

**Issue by riderx** [supabase/cli#1507]
I just switched to the new method to deploy all my functions:
`supabase functions deploy`

I would like a way to set in `config.toml` some function to be ignored during deploy all.

Furthermore, I have some demo function to help open-source maintainers create one, and this shouldn't be deployed.

Something like:
```toml
[functions.hello-world]
no_deploy = true
```
Would fix my issue
