### ISSUE TITLE
External auth provider secret may be optional

### ISSUE THREAD

**Issue by sweatybridge** [supabase/cli#1547]
**Describe the bug**

These fields are not required for native integration
- auth.external.apple.secret
- auth.external.google.secret

**To Reproduce**

```toml
[auth.external.apple]
enabled = true
client_id = "client_id"
secret = ""
redirect_uri = ""
url = ""
```

**Expected behavior**
Current workaround is to set them to a dummy value.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI [e.g. v1.60.0]
 - Version of supabase-js (if applicable) [e.g. v2.22.0]
 - Version of Node.js (if applicable) [e.g. v16.20.0]

**Additional context**
