### ISSUE TITLE
Generate types not working as expected

### ISSUE THREAD

**Issue by kirkstrobeck** [supabase/cli#1738]
# Describe the bug

Running `git diff` after `supabase gen types typescript --local > types/supabase-generated.d.ts` doesn’t work

### `.github/workflows/verify-generated-types.yml`

Locally, `pnpm list supabase` results in `1.106.1`

```
name: "verify-generated-types"

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID: "n/a"
      SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET: "n/a"

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.106.1

      - run: supabase db start
        working-directory: apps/web

      - run: npm run generate-types
        working-directory: apps/web

      - name: git diff
        run: |
          if ! git diff --ignore-space-at-eol --exit-code --quiet; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
```

### Produces this diff

This diff is unrelated to my code and seems like a Supabase change

```
Detected uncommitted changes after build. See status below:
diff --git a/apps/web/types/supabase-generated.d.ts b/apps/web/types/supabase-generated.d.ts
index 0973d07..73a5fd6 100644
--- a/apps/web/types/supabase-generated.d.ts
+++ b/apps/web/types/supabase-generated.d.ts
@@ -538,7 +538,6 @@ export interface Database {
           id: string
           name: string
           owner: string | null
-          owner_id: string | null
           public: boolean | null
           updated_at: string | null
         }
@@ -550,7 +549,6 @@ export interface Database {
           id: string
           name: string
           owner?: string | null
-          owner_id?: string | null
           public?: boolean | null
           updated_at?: string | null
         }
@@ -562,11 +560,17 @@ export interface Database {
           id?: string
           name?: string
           owner?: string | null
-          owner_id?: string | null
           public?: boolean | null
           updated_at?: string | null
         }
-        Relationships: []
+        Relationships: [
+          {
+            foreignKeyName: "buckets_owner_fkey"
+            columns: ["owner"]
+            referencedRelation: "users"
+            referencedColumns: ["id"]
+          }
+        ]
       }
       migrations: {
         Row: {
@@ -598,7 +602,6 @@ export interface Database {
           metadata: Json | null
           name: string | null
           owner: string | null
-          owner_id: string | null
           path_tokens: string[] | null
           updated_at: string | null
           version: string | null
@@ -611,7 +6[14](https://github.com/[repo]/actions/runs/7172863008/job/19530960495?pr=42#step:6:15),6 @@ export interface Database {
           metadata?: Json | null
           name?: string | null
           owner?: string | null
-          owner_id?: string | null
           path_tokens?: string[] | null
           updated_at?: string | null
           version?: string | null
@@ -6[24](https://github.com/[repo]/actions/runs/7172863008/job/19530960495?pr=42#step:6:25),7 +6[26](https://github.com/[repo]/actions/runs/7172863008/job/19530960495?pr=42#step:6:27),6 @@ export interface Database {
           metadata?: Json | null
           name?: string | null
           owner?: string | null
-          owner_id?: string | null
           path_tokens?: string[] | null
           updated_at?: string | null
           version?: string | null
Error: Process completed with exit code 1.
```

**To Reproduce**

1. Run `supabase gen types typescript --local > types/supabase-generated.d.ts` locally
2. Use github action provided above

**Expected behavior**

No diff.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version of CLI: 1.106.1
 - Version of Node.js: v18.12.1

May be related to https://github.com/supabase/cli/issues/1665

`major_version = 15` in my `.toml`
