### ISSUE TITLE
Download specific version of CLI

### ISSUE THREAD

**Issue by besteman** [supabase/cli#174]
# Feature request

Download specific version of CLI

A clear and concise description of what you want and what your use case is.

Be able to say what version of the CLI you want to download in the docs

## Additional context

Moving for `0.17.0` to `0.18.0` has broken our seeding the local db. we can get this now:

```
Error writing to tenant
{
  message: 'invalid value for parameter "search_path": "public, "',
  code: '22023',
  details: 'List syntax is invalid.',
  hint: null
}
Seeding tenant...
Error writing to countries
{
  message: 'invalid value for parameter "search_path": "public, "',
  code: '22023',
  details: 'List syntax is invalid.',
  hint: null
}
Seeding countries...
Error writing to geo_risk_context
{
  message: 'invalid value for parameter "search_path": "public, "',
  code: '22023',
  details: 'List syntax is invalid.',
  hint: null
}
```

And I don't see a way to go back to version `0.17.0`

**Comment by soedirgo** [comment]
I misconfigured the default config here - does setting `api.extra_search_path` to `["extensions"]` fix it?

**Comment by soedirgo** [comment]
As for downloading specific versions: all the binaries for previous versions are available from GitHub Releases, but if you're using Homebrew you'd need a workaround since it doesn't support multiple versions: https://stackoverflow.com/a/64125796

**Comment by besteman** [comment]
@soedirgo 

I had to put the `public` in the path to fix. Have not tried with 0.18.1 yet

```toml
[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public"]
```
