### ISSUE TITLE
pull environment variables into `config.toml`

### ISSUE THREAD

**Issue by theo-m** [supabase/cli#177]
# Feature request

## Is your feature request related to a problem? Please describe.

The new `config.toml` file is cool. I'd like to version it to keep track of its changes, but I don't want to commit e.g. my Google Oauth ClientID value.

## Describe the solution you'd like

For consistency I'd expect the CLI to pull things from my `.env.local` file already setup for my supabase thing. 

Don't know if the following is valid TOML, but just `"{{MY_SECRET}}"` would do as well.

```toml
[auth.external.google]
enabled = true
client_id = {GOOGLE_CLIENT_ID}
secret = {GOOGLE_OAUTH_SECRET}
```
