### ISSUE TITLE
Environment variables used in config.toml do not work in Github Actions

### ISSUE THREAD

**Issue by Aero56** [supabase/cli#1807]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have Google enabled as external OAuth provider for local development setting the client id and secret with environment variables.

I also have a github actions workflow to deploy to production. The problem is that this calls `supabase link` which expects these environment variables to be set, but these cannot be used in github actions.

```
> Run supabase link --project-ref $SUPABASE_PROJECT_ID
Error evaluating "env(GOOGLE_AUTH_CLIENT_ID)": environment variable GOOGLE_AUTH_CLIENT_ID is unset.
```

## To Reproduce

- Enable an external OAuth provider in `config.toml` using environment variables.

````
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_AUTH_CLIENT_ID)"
secret = "env(GOOGLE_AUTH_SECRET)"
````

- Add a github workflow running `supabase link` or `supabase db push`, this will error out

## Expected behavior

Supabase commands shouldn't care about these environment variables in `config.toml` because they are only used for local development.

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase cli: 1.123.4
- Version of Node.js: 18.15.0

**Comment by ianschmitz** [comment]
Agreed this threw me for a loop too. I had started thinking that maybe it was sync'ing these configuration values to the remote supabase instance, but that doesn't make sense for the `supabase link` command.

It seems to me that this should only matter while doing something like `supabase start` for starting up the containers locally.

**Comment by alexander-densley** [comment]
@obroomhall how did you set that env variable? is it a reposiroty secret on github?

**Comment by obroomhall** [comment]
@alexander-densley I would recommend reading the [documentation on GitHub Actions environment variables](https://docs.github.com/en/actions/learn-github-actions/variables), which gives various examples on how to provide environment variables, e.g.

```
name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
```

**Comment by tomo-09** [comment]
> @obroomhall how did you set that env variable? is it a reposiroty secret on github?

Hello,Please refer to my code. I was able to set dummy values and run GitHub Actions using this method.

```typescript
      - name: Start Supabase local development setup
        env:
          GOOGLE_CLIENT_ID: 'dummy-client-id'
          GOOGLE_SECRET: 'dummy-secret'
        run: supabase db start
```

**Comment by luizlevindiniz** [comment]
Hello guys. 
I was facing this issue in my next.js + supabase project. I had made some changes in my config.toml file to use custom smtp provider and auth, so when I was following this tutorial: https://supabase.com/docs/guides/deployment/managing-environments?queryGroups=environment&environment=staging the github action was failing due to those missing envs. 

As described above, using dummy envs has solved the problem:

```
name: Deploy Migrations to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_SUPABASE_PROJECT_ID }}
      SUPABASE_RESEND_SECRET: 'dummy-secret'
      SUPABASE_AUTH_GITHUB_CLIENT_ID: 'dummy-id'
      SUPABASE_AUTH_GITHUB_SECRET: 'dummy-secret'
      SUPABASE_AUTH_GOOGLE_CLIENT_ID: 'dummy-id'
      SUPABASE_AUTH_GOOGLE_SECRET: 'dummy-secret'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: SUPABASE_DB_PASSWORD=$SUPABASE_DB_PASSWORD supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
```
