### ISSUE TITLE
Issues Running `supabase start` within a devcontainer without `network_mode: "host"`

### ISSUE THREAD

**Issue by InnovateWorldio** [supabase/cli#1939]
**Describe the bug**
Unable to successfully run `supabase start` within a devcontainer when not using `network_mode: "host"`

**To Reproduce**
If I use the below compose.yml file from within the `.devcontainer` folder and run `supabase start` I receive the error `service not healthy: [supabase_rest_langchain supabase_edge_runtime_langchain]`

```
version: '3.8'
services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    user: vscode
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ports:
      - "5173:5173"
```

**Expected behavior**
If I use the below compose.yml file from within the `.devcontainer` folder and run `supabase start` everything works. I would expect to not need to use `network_mode: "host"`. 

``` 
version: '3.8'
services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    user: vscode
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    network_mode: "host"
``` 

**Additional Notes**
- Also due to the containers immediately being removed upon failing I am unable to get the container logs.
- I was also looking for a way to assign the supabase containers created with `supabase start` by passing in some parameters but am unable to do so like several other people mentioned across multiple issues.

**System information**
- Crash ID: 6c8ced45a99848e79c7d5339f7d2e74c
