### ISSUE TITLE
Config.toml env variable replacement fails

### ISSUE THREAD

**Issue by alex-ketch** [supabase/cli#210]
# Bug report

## Describe the bug

When trying to run `supabase start/stop` using CLI versions [`0.21.0`](https://github.com/supabase/cli/releases/tag/v0.21.0) or above, an error is shown if an env variable is used in the `config.toml`.
This used to work with `0.18.2`.

```sh
❯ source .env && supabase stop
Error: Error evaluating "env(GITHUB_CLIENT_ID)": environment variable GITHUB_CLIENT_ID is unset.
❯ echo $GITHUB_CLIENT_ID
some-client-id
```

**Config**
```toml
# other sections omitted
[auth.external.github]
enabled = true
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"
```

Let me know if more details are necessary.
Thanks!

## To Reproduce

1. Add the above config snippet to a Supabase project
2. Create a `.env` file with `GITHUB_CLIENT_ID=foo` as contents
4. run `source .env && supabase start`
6. See error

## Expected behavior

The env variables should be interpolated into the `config.toml`.
Ideally:
- misconfigurations in the TOML file shouldn't prevent stopping the local Docker containers
- env variable substitution should work throughout the config, and not just for auth providers

## System information

- OS: macOS 12.3
- Version of supabase-cli: `v0.22.4`
- Version of Node.js: `v16.13.0`

**Comment by soedirgo** [comment]
Thanks for the report! Will try to reproduce this.

**Comment by soedirgo** [comment]
Does it work if you do it like `GITHUB_CLIENT_ID=a GITHUB_SECRET=b supabase stop`?

**Comment by soedirgo** [comment]
I think you might need to use `export GITHUB_CLIENT_ID=a` etc. in your .env - `source` runs the script in a subshell so the envars are not passed to the `supabase` command.

**Comment by soedirgo** [comment]
As for your 2 points above:

> misconfigurations in the TOML file shouldn't prevent stopping the local Docker containers

Agree, I should fix this.

> env variable substitution should work throughout the config, and not just for auth providers

I'd like to keep it as is for now - the `env()` interpolation was really for things that *shouldn't* be committed to source control. I do think it's awkward that we only do it for external provider client IDs and secrets - might think up a better alternative at some point.

**Comment by alex-ketch** [comment]
> I think you might need to use `export GITHUB_CLIENT_ID=a` etc. in your .env - `source` runs the script in a subshell so the envars are not passed to the `supabase` command.
> 
> 
> 
> I'm not sure how/why it used to work though.

Before I didn't even need to run `source`. I would just alias my root `/.env` file to `/supabase/.env`. That seemed to work as intended.
And just to confirm, the env variables aren't loaded in automatically if I omit the `source` command either.

Issue with having to put `export ...` is that this then breaks the dotenv format and breaks usage with other tools.

I liked the aliasing workflow as it meant that we didn't have to juggle two sets of configs, and less chances of errors/accidental VCS commits.

I'll see if I can find a workaround, or have to adapt our workflow.

Thanks for investigating 🙏

**Comment by soedirgo** [comment]
As a workaround: https://unix.stackexchange.com/a/79077. Still not clean, but it works

**Comment by alex-ketch** [comment]
@soedirgo, I did a bit more testing and identified [`0.21.0`](https://github.com/supabase/cli/releases/tag/v0.21.0) as the speicfic version where this behaviour changed.
I have zero Go knowledge and no knowledge about the reason for the change, but am assuming it's the removal of the `godotenv` from the [`main.go` file](https://github.com/supabase/cli/commit/a1b8c6a0a2bda687ddba068c4606c7156fa7e3fd#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261) that stopped reading in the `.env` file values.

```diff
package main

import (
-  "github.com/joho/godotenv"
  "github.com/supabase/cli/cmd"
)

func main() {
- _ = godotenv.Load("supabase/.env")
-
  cmd.Execute()
}
```

**Comment by alex-ketch** [comment]
ah, that explains why my method of aliasing `.env -> ./supabase/.env` used to work then. I was just coopting the file.

I do think providing a more streamlined way for integrating with existing config conventions such as `.env` files would be desirable.
Please feel free to close this issue if you feel the above is out of scope, or want to track it another issue—new or reopening #177.
Either way, thanks for your time!

**Comment by soedirgo** [comment]
Yeah, I might revisit the secrets situation again. Thanks for your inputs!

**Comment by soedirgo** [comment]
@pocin I was able to reproduce this. Thanks for the catch!

**Comment by josuemy** [comment]
does the fix apply if I run `supabase start` through `npx`?

**Comment by iwasrobbed** [comment]
FYI for others who stumble on this:

>think you might need to use export GITHUB_CLIENT_ID=abcd

```env
export GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=id_abcd
export GOTRUE_EXTERNAL_GITHUB_SECRET=key_abcd
```

Without the export, it'll fail even if `echo $GOTRUE_EXTERNAL_GITHUB_CLIENT_ID` succeeds

(Probably would be good to put this in the docs or readme under https://github.com/supabase/gotrue#external-authentication-providers)

**Comment by lightstrike** [comment]
Thanks @iwasrobbed, saved me! 🌟

**Comment by luizlevindiniz** [comment]
Hello guys. 
I was facing this issue in my next.js + supabase project. I had made some changes in my config.toml file to use custom smtp provider and auth, so when I was following this tutorial: https://supabase.com/docs/guides/deployment/managing-environments?queryGroups=environment&environment=staging the github action was failing due to those missing envs. 

Using dummy envs has solved the problem:

```
name: Deploy Migrations to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_SUPABASE_PROJECT_ID }}
      SUPABASE_RESEND_SECRET: 'dummy-secret'
      SUPABASE_AUTH_GITHUB_CLIENT_ID: 'dummy-id'
      SUPABASE_AUTH_GITHUB_SECRET: 'dummy-secret'
      SUPABASE_AUTH_GOOGLE_CLIENT_ID: 'dummy-id'
      SUPABASE_AUTH_GOOGLE_SECRET: 'dummy-secret'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: SUPABASE_DB_PASSWORD=$SUPABASE_DB_PASSWORD supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
```
