### ISSUE TITLE
cli fails in github actions

### ISSUE THREAD

**Issue by Jayllyz** [supabase/cli#2305]
**Describe the bug**
`supabase db push` not ending correctly in github actions `ubuntu-latest` (self-hosted runner)

**To Reproduce**
```yaml
env:
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
  
...

  - if: github.ref == 'refs/heads/main'
    name: Setup Supabase CLI
    uses: supabase/setup-cli@v1
    with:
      version: latest

  - if: github.ref == 'refs/heads/main'
    name: Deploy migrations
    run: 
      |
      supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
      supabase db push -p ${{ env.SUPABASE_DB_PASSWORD }}
```
**Expected behavior**

Return success exit code

**Screenshots**
<img width="1462" alt="image" src="https://github.com/supabase/cli/assets/16305216/901e2882-74f2-47f2-ae70-ca018c84b10e">

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: Ubuntu 22.04
 - Version of CLI: 1.167.4
 - Version of Docker: [e.g. v25.0.3]
 - Versions of services: [output from `supabase services` command]

**Additional context**
If applicable, add any other context about the problem here.
 - Version of supabase-js [e.g. v2.22.0]
 - Version of Node.js 22
