### ISSUE TITLE
failed to connect to postgres: failed to connect to `host=aws-0-us-west-1.pooler.supabase.com user=postgres.efxwfeyycyccjijbttyb database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)

### ISSUE THREAD

**Issue by nyxb** [supabase/cli#2347]
Sent crash report: 422a12f177f64495897ba96e44751984

**Comment by sweatybridge** [comment]
I'm unable to reproduce on my side. How did you enter your project password? You can try

```bash
SUPABASE_DB_PASSWORD=abc supabase link
```

**Comment by nyxb** [comment]
> I'm unable to reproduce on my side. How did you enter your project password? You can try
> 
> ```shell
> SUPABASE_DB_PASSWORD=abc supabase link
> ```

Wow, okay, so it works this way, but why doesn't it work in this manner? Supabase link --password anypassword

**Comment by sweatybridge** [comment]
> but why doesn't it work in this manner? Supabase link --password anypassword

This is a regression. For some reason, cobra `BindPFlag` works with `StringVarP` but not `StringP`.

I will push a fix for `--password` flag.

**Comment by coolusaHD** [comment]
I have the same problem but with the latest CLI

Workflow: 
```
  deploy-supabase:
    name: 💻 Deploy Supabase
    environment: supabaseProduction
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-android, deploy-ios]
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🏗️ Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: 🔄️ Deploy Migrations to Production DB
        working-directory: frontend
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
```

I've updated my project to the latest version and using the right credentials
