### ISSUE TITLE
Till now it was successful but today it throw an error. Process completed with exit code 1. Did something changed?

### ISSUE THREAD

**Issue by Tananga** [supabase/cli#2351]
Hi. Im using github actions and so far everything was working great but today Im getting an error. Did something changed?

![Screenshot 2024-05-31 at 10 54 48](https://github.com/supabase/cli/assets/44244477/5ab13344-3ad6-4a72-866b-a51a5da80781)

And here is my workflow

```
jobs:
  deploy_dev_supabase:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_DEV }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_DEV }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db dump -f supabase/seed.sql --data-only
      - run: yes | supabase db reset --linked
```
