### ISSUE TITLE
CI function do not behave the same as local 

### ISSUE THREAD

**Issue by riderx** [supabase/cli#2461]
**Describe the bug**
All functions test pass 100% of the time in local but often fail in CI/CD env.

**To Reproduce*
In this repo: https://github.com/Cap-go/capgo
In local, if I do :
-  supabase start
- npm run minio:start && npm run minio:seed ( I use minio i didn't migrate to s3 api of supabase yet)
-  supabase functions serve 
- deno test --allow-all supabase/functions/tests/* --env=supabase/.env.test --import-map=supabase/functions/import_map.json --fail-fast
- All test pass.
- In github action 
```yml
name: Run tests

on:
  push:
    branches:
      - 'main'

jobs:
  test_base_sql:
    runs-on: ubuntu-latest
    name: "Run test"
    steps:
      - name: "Checkout capgo"
        uses: actions/checkout@v4
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.176.10
      - name: Set env PROD
        run: echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASS }}" >> $GITHUB_ENV    
      - name: 🍜 Prepare Supabase PROD
        run: supabase link --project-ref xvwzpoazmxkqosrdewyv
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
      - name: Run Supabase Start
        run: ENV=local supabase start
      - run: supabase test db
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: "Start minio"
        run: npm run minio:start && npm run minio:seed
      - run: deno test --allow-all supabase/functions/tests/* --env=supabase/.env.test --import-map=supabase/functions/import_map.json
```

Both env run the same way and yet the CI/CD fail, you can see the history of github actions, some endpoint timeout weirdly 

**Expected behavior**
Localhost should fail the same way as CI/CD
