### ISSUE TITLE
Podman complains about health check syntax errors

### ISSUE THREAD

**Issue by thenbe** [supabase/cli#2532]
There are two containers where the healthcheck fails in podman due to a syntax error, studio and pgmeta.

1. pgmeta

https://github.com/supabase/cli/blob/71c2abdac3ab092c8bf8ac84b40f77b20821dfb3/internal/start/start.go#L901

2. studio

https://github.com/supabase/cli/blob/71c2abdac3ab092c8bf8ac84b40f77b20821dfb3/internal/start/start.go#L947

When I change these two lines to a noop, the containers start successfully. For example:

```diff
-					Test:     []string{"CMD", "node", `--eval='fetch("http://127.0.0.1:8080/health").then((r) => {if (r.status !== 200) throw new Error(r.status)})'`},
+					Test:     []string{"CMD", "node", `--version`},
```

Log (it's not pretty):

```
Health:
  FailingStreak: 2

  Log:

  - End: 2024-07-18T20:19:42.26441464+03:00
    ExitCode: 1
    Output: "[eval]:1\n'fetch(\"http://127.0.0.1:3000/api/profile\",\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nSyntaxError: Invalid or unexpected token\n    at makeContextifyScript (node:internal/vm:185:14)\n    at node:internal/process/execution:107:22\n    at [eval]-wrapper:6:24\n    at runScript (node:internal/process/execution:101:62)\n
alScript (node:internal/process/execution:133:3)\n    at node:internal/main/eval_string:51:3\n\nNode.js v20.15.0"
    Start: 2024-07-18T20:19:42.236295233+03:00

  - End: 2024-07-18T20:19:52.356312244+03:00
    ExitCode: 1
    Output: "[eval]:1\n'fetch(\"http://127.0.0.1:3000/api/profile\",\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nSyntaxError: Invalid or unexpected token\n    at makeContextifyScript (node:internal/vm:185:14)\n    at node:internal/process/execution:107:22\n    at [eval]-wrapper:6:24\n    at runScript (node:internal/process/execution:101:62)\n
alScript (node:internal/process/execution:133:3)\n    at node:internal/main/eval_string:51:3\n\nNode.js v20.15.0"
    Start: 2024-07-18T20:19:52.328284657+03:00
```

Ref: https://github.com/supabase/cli/pull/2359
