### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#265]
# Feature request

Would be really nice to be able to use [Podman](https://podman.io/) instead of Docker. Podman is more lightweight, and from my understanding can run containers rootless

**Comment by zakaria-chahboun** [comment]
+1

**Comment by zakaria-chahboun** [comment]
Yes. You can! Just follow these instructions:

Install `podman` `podman-docker` and `docker-compose`

*i'm using linux pop_os*

```bash
sudo apt-get -y install podman
sudo apt-get -y install podman-docker
sudo apt-get -y install docker-compose
```

Now. You have to clone the supabase repo:
```bash
git clone --depth 1 https://github.com/supabase/supabase
```

Then:
```bash
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env
```

Now you have to configure Docker Hub mirror in /etc/containers/registries.conf:

```bash
sudo nano /etc/containers/registries.conf
```

Add these lines to the end of file:
```toml
unqualified-search-registries = ['docker.io']

[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
prefix = "docker.io"
location = "docker.mirrors.ustc.edu.cn"
```

Now. You are ready to install supabase studio:
```bash
sudo docker-compose up
```

Finally. visit http://localhost:3000 to start using Supabase Studio.

In case you face this error:

> ERROR: for db  error preparing container 22e6838a1fd10267d63f69ef400000a84a1a857a5e46718003f8a5f63388bb0f for attach: cannot listen on the TCP port: listen tcp4 :5432: bind: address already in use

Just change the `POSTGRES_PORT` in `.env` file.
