### ISSUE TITLE
Allow reading config values from .env file

### ISSUE THREAD

**Issue by amrnn90** [supabase/cli#278]
# Feature request
Hello, I tried looking through the docs for a way to set secret values in `config.toml` by reading a `.env` file, but I couldn't find anything.

Searching the issues I found this one #210 which seems related to what I am asking for, but I couldn't understand how to get things working.

I tried doing this in my `config.toml` file:
```toml
[auth.external.github]
client_id = "env(GITHUB_CLIENT_ID)"
enabled = true
secret = "env(GITHUB_SECRET)"
```

and I created a `.env` file:
```
export GITHUB_CLIENT_ID=...
export GITHUB_SECRET=...
```

and finally started supabase by running this command:
```
(source .env && supabase start)
```

Which doesn't seem to work, trying to log in using github causes supabase to create a url that looks like this:
```
https://github.com/login/oauth/authorize?client_id=env%28GITHUB_CLIENT_ID%29
```

So it seems to copy the value stored in `config.toml` literally.

Any help is appreciated, thanks!
