### ISSUE TITLE
Recent release breaks migrations that use 'create index concurrently'

### ISSUE THREAD

**Issue by Daniel-Ash** [supabase/cli#2898]
**Describe the bug**

This occurred in a github action that uses the latest version of the CLI by default. Reverting to an older version (I picked 1.220.0 for no good reason) resolves the issue.

**To Reproduce**
1. Install the latest version of the CLI ([v1.223.10](https://github.com/supabase/cli/releases/tag/v1.223.10) as I write this).
2. Add a migration with `CREATE INDEX CONCURRENTLY` 
3. Run supabase start
4. Receive the following error:
  `Applying migration [redacted].sql...
  Stopping containers...
  ERROR: CREATE INDEX CONCURRENTLY cannot be executed within a pipeline (SQLSTATE 25001)`

**Expected behavior**
Migration should run without fail.

**System information**
 - Version of CLI: v1.223.10

**Comment by sweatybridge** [comment]
This might be due to a version bump to postgres from 15.1 to 15.6. Could you check the contents of `supabase/.temp/postgres-version`, if it exists?

**Comment by Daniel-Ash** [comment]
I've only observed this in a github action so far + haven't attempted to reproduce elsewhere - any thoughts as to how I could validate that there?

**Comment by Daniel-Ash** [comment]
I'm not sure it has anything to do with a linked project, because it is a CI action that spins up a fresh supabase on the runner, runs the migrations, lints, tests, etc. I haven't experienced this issue against an actual project - it happened when supabase start applied an old migration to the fresh db.

But for clarity, our staging and production dbs are on 15.1.1.44

Here is the github action:

``` 
name: Supabase CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./supabase-db/supabase

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest 
      - name: Start database
        run: supabase db start

      - name: Lint database
        run: supabase db lint

      - name: Run database tests
        run: |
          supabase db test 
```
