### ISSUE TITLE
CLI version v1.223.10 breaking change causes deployment GitHub action to fail because of missing smtp setting in config file

### ISSUE THREAD

**Issue by khera** [supabase/cli#2899]
**Describe the bug**

Using a GitHub action to push migrations to the hosted instance fails with the current CLI, because it is now fatal to not have an smtp host defined. The local CLI development defaults to in bucket, so this is not set in my config file.

**To Reproduce**

Using the following GitHub actions:

```yaml
jobs:
    supabase-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Prep Supabase CLI
              uses: supabase/setup-cli@v1
              with:
                version: latest
            - run: supabase link --project-ref ${{ inputs.PROJECT_ID }}
            - run: supabase db push
```

pulls the latest version of the cli, which is v1.223.10 currently. My project locally is still using CLI v1.219.2 where everything works. When running the link command, it fails with this error:

```
Missing required field in config: auth.email.smtp.host
Try rerunning the command with --debug to troubleshoot the error.
```

Then it exits.

There's no reason to have the local CLI development configuration set this variable, as it uses inbucket.

**Expected behavior**

The deploy should succeed like it always has with my config file, or the version should be bumped for the breaking change.

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: [e.g. Ubuntu 22.04] Github default worker OS
 - Version of CLI: [e.g. v1.60.0]  v1.223.10 or whatever GitHub action pulls for `latest`.
 - Version of Docker: [e.g. v25.0.3] n/a
 - Versions of services: [output from `supabase services` command] nothing is running in my action but the CLI.

**Additional context**
If applicable, add any other context about the problem here.
 - Browser [e.g. chrome, safari] safari
 - Version of supabase-js [e.g. v2.22.0] 2.46.1
 - Version of Node.js [e.g. v16.20.0] whatever Github actions is using

**Comment by khera** [comment]
Clarification: it seems that if *any* `auth.email.smtp` settings are made, you now require *all* (host, port, user, pass) of them to be set.

My current configuration is

```toml
[auth.email.smtp]
admin_email = "support@mydomain.com"
sender_name = "MyProject DEV"
```

Now it is demanding I set all the other fields, but there's no guidance as to what those should be to work with inbucket in the sample `config.toml` in a new project. I set the following, but the auth service cannot still send any email, it returns 500 error status.

```toml
host = "localhost"
port = 54325
user = "email"
pass = "anything"
```

It would be helpful to add those notes in the config.toml in a new project, and to have a "migrate" function of the CLI to bring my config file up to current, keeping existing settings I changed.

**Comment by sweatybridge** [comment]
Thanks for reporting this issue. I wasn't expecting users to configure inbucket `[auth.email.smtp]` because the original comment was to configure a [production ready](https://github.com/supabase/cli/blob/develop/pkg/config/templates/config.toml#L129) custom smtp server. However, we also didn't perform any validations previously so this unintentionally became a breaking change.

Going forward, I wouldn't recommend updating `smtp` to inbucket host and port because those values won't make sense for branching use cases. We are also planning to switch to mailpit for better UI.

But if this is necessary to unblock, you can use the following settings for the time being.

```toml
[auth.email.smtp]
host = "inbucket"
post = 2500
user = "anything"
pass = "anything"
```

I will update this thread again after we come to a firm decision internally.

**Comment by khera** [comment]
Thanks for the info. I set up the config as you show above, keeping my admin_email and sender_name,  (and restarted local dev) but I continue to get the error sending the recovery mail, Error sending recovery email

```
  status: 500,
  code: 'unexpected_failure'
```

on the dashboard it shows this in the auth log:

```
{
  "code": 500,
  "message": "An error has occurred: fetch failed",
  "requestId": "198e150f-4b2e-4234-925b-703a717fad71"
}
```

**Comment by avallete** [comment]
I think there's a circular issue between `gotrue` and `inbucket`. If you provide a non-empty username/password, it expects encryption to be enabled, which fails with inbucket. The way I got inbucket and SMTP working together was by disabling the validation for SMTP user/password in the cli source code. With this configuration, emails are sent properly to inbucket:

```toml
# Use a production-ready SMTP server
[auth.email.smtp]
host = "inbucket"
port = 2500
admin_email = "admin@email.com"
sender_name = "Admin Custom"
```

Otherwise, as long as `smtp.user` and `smtp.pass` are set to non-empty values, the auth container throws a 500 error:

```
{"user_email":"XXXX@gmail.com","user_id":"56e9b859-970b-4f06-80e7-11f305f4188b"}},"component":"api","error":"unencrypted connection","level":"error","method":"POST","msg":"500: Error sending invite email","path":"/invite","referer":"http://127.0.0.1:3000","remote_addr":"192.168.97.14","request_id":"be3e432d-af74-4f05-b8aa-35dc5df7083a","time":"2024-11-22T14:50:19Z"}
```

The solution I found to retain SMTP validation and allow email/sender customization is to support `sender_name` and `admin_email` under the `inbucket` section of the configuration. This is a draft proposal as it'll still be a breaking change that'll require config update.

See: [https://github.com/supabase/cli/pull/2908](https://github.com/supabase/cli/pull/2908)

**Comment by avallete** [comment]
@khera you should now be able to use a custom admin_email and sender_name for your `inbucket` config by removing those values from your `smtp` config and placing them under your `inbucket` config instead like so:

```toml
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326
admin_email = "support@mydomain.com"
sender_name = "MyProject DEV"
```

Then you should be able to try it out with the latest cli `@beta` tag like so: `npx supabase@beta start`.
