### ISSUE TITLE
config.toml do not accepts env variables for `auth.hook.send_email.uri`

### ISSUE THREAD

**Issue by KajSzy** [supabase/cli#3003]
**Describe the bug**
I am unable to use env variables in `config.toml` file to define custom email hooks url

**To Reproduce**

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Define urls inside `.env` file
2. Reference them inside config.toml file
```toml
[auth.hook.send_email]
enabled = true
uri = "env(SUPABASE_SEND_MAIL_HOOK_URL)"
secrets = "env(SUPABASE_MAIL_SECRET)"
```
3. Run `supabase db reset` script

**Expected behavior**
I expect it to allow using env variables for those config.toml properties

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: MacOS
 - Version of CLI: 2.2.1
 - Version of Docker: 27.4.0
 - Versions of services: 
![Zrzut ekranu 2025-01-2 o 00 16 04](https://github.com/user-attachments/assets/e30a163f-4dd3-45b7-98da-99f8a9fac9cd)
