### ISSUE TITLE
v 2.12.1 breaks github actions

### ISSUE THREAD

**Issue by mosnicholas** [supabase/cli#3138]
**Describe the bug**
Supabase on the github CI is consistently failing with version 2.12.1. It works with v2.12.0

**To Reproduce**
create a basic github action with the following:
```
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Run supabase
        run: supabase start -x imgproxy,edge-runtime,logflare,realtime,studio --debug
```

you'll see the error:

![Image](https://github.com/user-attachments/assets/dd1fc91c-043f-4c45-96a8-cd96859013db)

**Expected behavior**
SHould be working.

**Screenshots**

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: [e.g. Ubuntu 22.04]
 - Version of CLI: [e.g. v1.60.0]
 - Version of Docker: [e.g. v25.0.3]
 - Versions of services: [output from `supabase services` command]

**Additional context**
If applicable, add any other context about the problem here.
 - Version of supabase-js [e.g. v2.22.0]
 - Version of Node.js [e.g. v16.20.0]
