### ISSUE TITLE
Function deployment is non-deterministic

### ISSUE THREAD

**Issue by KaiserKarel** [supabase/cli#3325]
**Describe the bug**
After running supabase functions deploy, sometimes one observes a `module not found error`. Rerunning with the same program fixes this deployment

**To Reproduce**

Using this CI flow, we've observed this happen maybe 4 times over the last 3 months.

```
name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ****
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy --project-ref $PROJECT_ID
```

Rerunning the job immediately fixes the issue.

**Expected behavior**

When the CLI version is unaltered and the edge function code unaltered, deployments should be idempotent.

**Screenshots**

<img width="737" alt="Image" src="https://github.com/user-attachments/assets/adc8cad6-477e-4f61-b0f7-0350698704f6" />
