### ISSUE TITLE
Failed to connect to postgres in GitHub Actions

### ISSUE THREAD

**Issue by MarDi66** [supabase/cli#3326]
**Describe the bug**
When running my GitHub action that should push new migrations files to my remote Supabase, an error pops-up:
``` shell
failed to connect to postgres: failed to connect to `host=db.***.supabase.co user=postgres database=postgres`: dial error (dial tcp [2a05:d018:135e:1603:9844:227e:3d2b:69c9]:5432: connect: network is unreachable) 
```

This GitHub Action worked well before, but it doesn't anymore, and I didn't change any Supabase-related config/file.

**To Reproduce**
Here's my GitHub Action: 
``` yaml
name: Supabase Migrations (Production deployment)

on:
  deployment_status:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Deployment Status: ${{ toJson(github.event.deployment_status) }}"
          echo "Contains Production: ${{ contains(github.event.deployment_status.environment, 'Production') }}"

  run-migrations:
    if: |
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.environment, 'Production')
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_MAIN_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_MAIN_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1.4.0

      - name: Push Migrations to Supabase
        run: |
          cd apps/database
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
```

**Expected behavior**
Push the migrations files to remote Supabase on deployment success event

**Screenshots**
<img width="1611" alt="Image" src="https://github.com/user-attachments/assets/6537b9ff-0e5a-4b00-99ad-58350e3fa67e" />

**System information**
 - Version of OS: ubuntu-latest
 - Version of CLI: v1.4.0
 - Version of Docker: Not applicable
 - Versions of services:
       SERVICE IMAGE         │      LOCAL                    │   LINKED
    supabase/postgres       │ 15.6.1.139                   │  15.6.1.139
    supabase/gotrue           │ v2.168.0                     │ v2.168.0
    postgrest/postgrest       │ v12.2.3                         │ v12.2.3
    supabase/realtime         │ v2.34.40                       │ -
    supabase/storage-api   │ v1.17.1                            │ -
    supabase/edge-runtime  │ v1.67.2                       │ -
    supabase/studio             │ 20250224-d10db0f   │ -
    supabase/postgres-meta │ v0.86.1                     │ -
    supabase/logflare             │ 1.12.5                        │ -
    supabase/supavisor         │ 2.4.12                         │ -

**Additional context**
Running `supabase db push` locally works

**Comment by devsrealm** [comment]
Use latest:

```
      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
```
