### ISSUE TITLE
over_email_send_rate_limit -running local dev - only 2 emails sent in past hour

### ISSUE THREAD

**Issue by magick93** [supabase/cli#3353]
# Bug report
this is clearly a bug that has been introduced in a recent upgrade. 

I've been running this project locally for over a year now and have never had this issue. I decided to update the supabase cli, and now get this error. 

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When performing a `supabase.auth.signUp()` invocation I now get:

```
supabase.error: {
      "__isAuthError": true,
      "name": "AuthApiError",
      "status": 429,
      "code": "over_email_send_rate_limit"
    }
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. run `supabase start` - this issue is occurring locally, not self hosted, not hosted by supabase.com
1. In Typescript / Javascript, peform a `signUp()` action, eg:

```ts
return await supabase.auth.signUp({
      email: form.data.email,
      password: form.data.password,
      options: {
        emailRedirectTo: `${url.origin}/auth/callback?next=/auth/onboarding`,
        data: userData(),
      }
    });
```
3. This is now fails with error

```js
supabase.error: {
      "__isAuthError": true,
      "name": "AuthApiError",
      "status": 429,
      "code": "over_email_send_rate_limit"
    }
```

## System information

- OS: Ubuntu 24.04.2 LTS
-  `"@supabase/ssr": "^0.5.2"`
-  `"@supabase/supabase-js": "^2.47.10"`

## Additional context

I notice that the dev email appliation has also changed. I discovered this bug after running cypress tests that usually pass without any issue. The first failed. I noticed that the dev email client had changed. I adjusted the test, it still failed. And at this point it had sent 2 emails. 

And this is running completely locally, so I dont see why any email limit would even make sense. 

# config.toml

Here are the relevant sections of my local config.toml:

```toml

[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
smtp_port = 54325
# pop3_port = 54326

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://127.0.0.1:3000", "http://localhost:5173/auth/callback"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow testing manual linking of accounts
enable_manual_linking = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

```

**Comment by Hallidayo** [comment]
Hi all, I've moved this one over to the cli repo as it seems more related in the cli repo.

**Comment by silentworks** [comment]
This is a bug as I don't have custom SMTP setup in any of my local projects and they are getting rate limited. I've upped the limit using the new configs. But this shouldn't have happened as the comment above the config states it should only happen if `auth.email.smtp` is enabled and in my case it's not. As a matter of fact the smtp configs are commented out in my `config.toml` file.

```toml
[auth.rate_limit]
# Number of emails that can be sent per hour. Requires auth.email.smtp to be enabled.
email_sent = 100
# Number of SMS messages that can be sent per hour. Requires auth.sms to be enabled.
sms_sent = 30
# Number of anonymous sign-ins that can be made per hour per IP address. Requires enable_anonymous_sign_ins = true.
anonymous_users = 30
# Number of sessions that can be refreshed in a 5 minute interval per IP address.
token_refresh = 150
# Number of sign up and sign-in requests that can be made in a 5 minute interval per IP address (excludes anonymous users).
sign_in_sign_ups = 30
# Number of OTP / Magic link verifications that can be made in a 5 minute interval per IP address.
token_verifications = 30
```
