### ISSUE TITLE
Linking to project using CLI in CI environment not working.

### ISSUE THREAD

**Issue by CalvinWilkinson** [supabase/cli#3500]
**Describe the bug**
I am trying to link to my project in the GitHub CI environment by using the `supabase link --project-ref --password` command. 
When doing this, I get the following output:
```bash
WARN: no SMS provider is enabled. Disabling phone login
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=aws-0-us-west-1.pooler.supabase.com user=postgres.hypsasklbmkqagnwhkca database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

I don't know if this is related to the issue below, but I have been having issues related to this for months.  This time, the issue has changed from what was described in the issue below to the output described above.
- supabase/cli#2956

I tried 2 different attempts this morning.  The first attempt was with supabase CLI version `v2.22.4` with the command `supabase link --project-ref` with the GitHub output below:
```bash
 $projRefId = "hypsasklbmkqagnwhkca";
  supabase link --project-ref "$projRefId";
  shell: /usr/bin/pwsh -command ". '{0}'"
  env:
    OWNER_NAME: EngagedAgility
    REPO_NAME: EAClassManager
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
    SUPABASE_ACCESS_TOKEN: ***
    SUPABASE_DB_PASSWORD: ***
WARN: no SMS provider is enabled. Disabling phone login
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=aws-0-us-west-1.pooler.supabase.com user=postgres.hypsasklbmkqagnwhkca database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```
My second attempt was after I updated the supabase CLI version to the latest version as of this issue to version `v2.22.6`.  I also tried to use the command with the `--password` flag, but got the GitHub output above.

I know you mentioned project inactivity in issue supabase/cli#2956, but my project is not inactive.  We are 1 to 2 weeks away from paying and going to production, so the project has been active due to me doing testing before we go live, but I just checked again, and we are indeed not inactive.

> [!NOTE]
> When running this command locally on my Windows machine, it works with no issue. 

**To Reproduce**
1. Create a supabase project
2. Verify the supabase CLI is `v2.22.6`
3. Create a workflow with a job and a step to link to a supabase project
4. In the step, use the `supabase link --project-ref --password` command.
5. Observe the result. (If it exists)

> [!NOTE]
> My workflow is running on the latest version of Ubuntu, which is `v24.04.2` 

**Expected behavior**
I expect the CLI to connect to my supabase project with no issues.

**System information**
NONE.  The'- create-ticket' command did not get any information.

**Additional context**
If applicable, add any other context about the problem here.
 - Version of supabase-js [e.g. v2.22.0]
 - Version of Node.js [e.g. v16.20.0]

I reran the command in my CI environment using the `--create-ticket` command, but the output did not show
any additional information as shown in the **System Information** section.  Below is the output I got with the additional flag.
```bash
  $projRefId = "hypsasklbmkqagnwhkca";
  $dbPassword = "***";
  supabase link --project-ref "$projRefId" --password "$dbPassword --create-ticket";
  shell: /usr/bin/pwsh -command ". '{0}'"
  env:
    OWNER_NAME: EngagedAgility
    REPO_NAME: EAClassManager
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
    SUPABASE_ACCESS_TOKEN: ***
    SUPABASE_DB_PASSWORD: ***
WARN: no SMS provider is enabled. Disabling phone login
Connecting to remote database...
failed to connect to postgres: failed to connect to `host=aws-0-us-west-1.pooler.supabase.com user=postgres.hypsasklbmkqagnwhkca database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

**Comment by sweatybridge** [comment]
The latest CLI release no longer requires the database password for linking.

```
npx supabase@latest link
```

Please give it another try and let me know if it still errors.

**Comment by CalvinWilkinson** [comment]
> The latest CLI release no longer requires the database password for linking.
> 
> ```
> npx supabase@latest link
> ```
> 
> Please give it another try and let me know if it still errors.

I was wondering with the new API and publishable keys that have been released, what would I use in place of the `SUPABASE_ACCESS_TOKEN`?  I have not used or really looked into the new API and JWT key system yet.

I need it to use the `supabase link --project-ref` command.  I assume that we would use the new JWT keys?

**Comment by sweatybridge** [comment]
The supabase access token is your [personal access token](https://supabase.com/dashboard/account/tokens). It is tied to your account.

The new api keys are unique to your project's PostgREST api.

You can run `supabase login` to create a personal access token.

**Comment by CalvinWilkinson** [comment]
@sweatybridge 

I updated my workflow to do the following:
```yml
name: 🚀Preview Release 
run-name: Preview Release


defaults:
  run:
    shell: pwsh


on:
  push:
    branches: ["release"]


env:
  OWNER_NAME: "${{ vars.OWNER_NAME }}"
  REPO_NAME: "${{ vars.REPO_NAME }}"


jobs:
  get_version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ vars.DENO_VERSION }}

      - name: Get Version
        id: get-version
        run: deno run -EW "${{ github.workspace }}/.github/cicd-scripts/get-version.ts";


  run_db_migrations:
    name: Run Database Migrations
    needs: [get_version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI (${{ vars.SUPABASE_CLI_VERSION }})
        uses: supabase/setup-cli@v1
        with:
          version: ${{ vars.SUPABASE_CLI_VERSION }}

      - name: Reset Database
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.EA_SUPA_PAT_STANDARD_PREV }}
        run: |
          projRefId="${{ vars.EA_SUPA_PROJ_REF_ID_PREV }}"
          supabase link --project-ref "$projRefId"
          echo "y" | supabase db reset --linked
```

When doing this, I get the following error:
```bash
Seeding data from supabase/seed.sql...
failed to send batch: ERROR: function gen_salt(unknown) does not exist (SQLSTATE 42883)
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

This is the same error I get when running these commands locally.  My understanding is the reason for this is because it is taking my local 'config.toml' file into account?  At lease some of my research is pointing to this as the issue.

I also tried to use the direct db connection as well but I start to get SSL issues and no matter what I try, I cannot get it to work.
Below is the type I get when using a direct db connection:
```bash
  projRefId="hypsasklbmkqagnwhkca"
  dbPassword="***"
  dbUrl="postgresql://postgres.${projRefId}:${dbPassword}@aws-0-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require"
  echo "y" | supabase db reset --db-url "$dbUrl"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    OWNER_NAME: EngagedAgility
    REPO_NAME: EAClassManager
    SUPABASE_INTERNAL_IMAGE_REGISTRY: ghcr.io
WARN: no SMS provider is enabled. Disabling phone login
Do you want to reset the remote database? [y/N] y
Resetting remote database...
failed to connect to postgres: failed to connect to `host=aws-0-us-west-1.pooler.supabase.com user=postgres.hypsasklbmkqagnwhkca database=postgres`: server error (FATAL: SSL connection is required (SQLSTATE XX000))
Try rerunning the command with --debug to troubleshoot the error.
Error: Process completed with exit code 1.
```

Any insight into what is going on here?
