### ISSUE TITLE
Add hooks to cli commands

### ISSUE THREAD

**Issue by osaxma** [supabase/cli#501]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, when I would like to run a command before or after certain supabase cli commands, I've to run that manually or write a script to run both commands.

## Describe the solution you'd like

It would be useful if we could hook commands to supabase cli commands. One idea comes to mind is to define them within the `config.toml` such as:

```toml
[hooks]

post_start ='psql postgresql://postgres:postgres@localhost:54322/postgres < custom_seed.sql'
post_start='dart run generate_types.dart'

post_db_reset='dart run generate_types.dart'

pre_stop='pg_dump postgresql://postgres:postgres@localhost:54322/postgres -n public > dumps/schema_dump.sql' 
```
> _excuse my poor `toml` -- I'm sure this could be structured in a better way for sub-commands (e.g. supabase db reset)._

In the above example, the idea is that each lifecycle command (e.g. stop, start, reset) can have pre- or post-hook(s).
