### ISSUE TITLE
Schema supabase_functions does not exist (local development)

### ISSUE THREAD

**Issue by nereolopez** [supabase/cli#925]
# Bug report

## Describe the bug
When trying to create a Database Webhook function in my local Supabase Studio, I get the following error: 
`Failed to create hook: schema "supabase_functions" does not exist`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start local supabase dev environment `supabase start` (while Docker is running)
2. Open the local Supabase Studio (http://localhost:54323/project/default)
3. On the left menu, go to Database
4. Select Webhooks, enable them in Alpha and create a test webhook
5. See error `Failed to create hook: schema "supabase_functions" does not exist`

## Expected behavior

The Database Webhook should have been created correctly

## Screenshots

![image](https://user-images.githubusercontent.com/5878234/223433051-521fc8f9-749a-4506-92df-0c39e3ceb1b1.png)

## System information

- OS: Windows 10
- Browser (if applies) Chrome 
- Version of Supabase CLI: 1.40.1 (latest available in Scoop as of today)

## Additional points
1. When doing it on the cloud instance, the Database Webhook is created correctly. If I then go to Table Editor => Schema `supabase_functions` -> Table `hooks` I see it empty. Is this correct? From the error above I assumed created Webhooks would be stored there. I see the Webhook in Database => Webhooks though.
2. Are Webhooks captured as part of migrations and added to the sql file when a new migration is created? 

Thanks!

**Comment by sweatybridge** [comment]
This should be fixed on latest CLI for both pg14 and pg15. Feel free to reopen if that's still not the case.

**Comment by nereolopez** [comment]
Hi, thanks for the fix! I see [Scoop](https://github.com/supabase/scoop-bucket/blob/main/supabase.json) is still few versions behind (1.40.1) as of now compared to [NPM](https://www.npmjs.com/package/supabase) updated yesterday to 1.42.7. Any timeline on when will Scoop be updated?

Thanks!

**Comment by basitanwer** [comment]
Its not happening to me locally but in GitHub actions.
This is the migration command

```sql
CREATE TRIGGER revalidate_index AFTER INSERT OR DELETE OR UPDATE ON public.<TABLE> FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('<HTML>', 'GET', '{"Content-type":"application/json"}', '{"secret":"TOKEN"}', '1000');
```

and my `ci.yaml` looks like this

```yaml
name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > supabase/types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
```

And the error I get on running the migration is

```
Error: ERROR: schema "supabase_functions" does not exist (SQLSTATE 3F000)
```

**Comment by sweatybridge** [comment]
The default version installed by setup-cli is slightly behind. You can resolve this error by specifying the latest version

```yaml
- uses: supabase/setup-cli@v1
  with:
    version: latest
```

**Comment by Pictor13** [comment]
@sweatybridge  I'm having the same error while trying migrating one project's db to another project, following the guide at https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#migrate-your-project.

Runing `psql   --single-transaction   --variable ON_ERROR_STOP=1   --file roles.sql   --file schema.sql   --file data.sql   --dbname "$NEW_DB_URL"`
returns: 
```
psql:data.sql:7556: ERROR:  schema "supabase_functions" does not exist
```

Supabase CLI is 1.93.0, the latest on NPM, from 10 days ago (although I see tags till 1.99.0 here on Github).

Not sure what the error means and why it keeps appearing; maybe a regression?

**Comment by thibaudlef** [comment]
I got this issue but it was solved by enabling webhooks in destination database.

**Comment by rumfiske** [comment]
> @Pictor13 @kingraphaii I got this issue but it was solved by enabling webhooks in destination database.

You sir was the solution to my 5 hours long search on the internet. **THANK** you.

I want to mention this also fixses the error, when trying to dump the data from a db.:

Dumping data from remote database...
pg_dump: error: query failed: ERROR:  permission denied for table hooks
pg_dump: detail: Query was: LOCK TABLE "supabase_functions"."hooks" IN ACCESS SHARE MODE

**Comment by CernyMatej** [comment]
@thibaudlef
where exactly did you enable it, please?

**Comment by Suzan-Dev** [comment]
> @thibaudlef where exactly did you enable it, please?

In the platform, navigate to "Database" from sidebar -> "Webhooks" under platform section & enable it

**Comment by venku122** [comment]
Is there a way to enable webhooks programmatically or via the sql script?

I am running `supabase migration up` on my test container using image `supabase/postgres:15.1` and the migration requiring webhooks is failing every time.

**Comment by Harris-Ferguson** [comment]
Is there a way to enable the webhooks for Branches? I'm finding that my branch builds are giving me this error when they spin up: 
<img width="672" alt="Screenshot 2024-12-12 at 12 02 32 PM" src="https://github.com/user-attachments/assets/53958d21-d407-47f7-94ce-21f899d730c8" />

 
<img width="181" alt="Screenshot 2024-12-12 at 12 02 50 PM" src="https://github.com/user-attachments/assets/3f5bf69c-f4d5-44c1-b485-24d007572b81" />

**Comment by sweatybridge** [comment]
Yes, you can enable it via [config.toml](https://supabase.com/docs/guides/cli/config). For eg.

```toml
[experimental.webhooks]
enabled = true
```
